### ISSUE TITLE
Drupal 8 test should run tests on custom modules

### ISSUE THREAD

**Issue by jhedstrom** [phase2/grunt-drupal-tasks#121]
With the adoption of PHPUnit in Drupal 8, hopefully more projects will write unit tests as part of development. 

I think the goal would be to take our current `grunt test`, which is just an alias for `grunt behat`, and transform it such that

* `grunt test:drupal` runs the `run-tests.sh` script (core's test runner)
* `grunt test:behat` would do what `grunt behat` does
* `grunt test` would run all tests.

**Comment by arithmetric** [comment]
Next steps:
- Include PHPUnit and dependencies OR use the PHPUnit included with the D8 build
- GDT config for identifying tests to run
- Add Grunt task for running PHPUnit (use Grunt plugin or direct shell command)

Note: This depends on a operational Drupal docroot.

**Comment by jhedstrom** [comment]
In addition to PHPUnit, we'll want to run Kernel and Web/Browser tests. Essentially:

```
core/scripts/run-tests.sh --directory=./modules/custom
```

**Comment by jhedstrom** [comment]
This is an example of the `run-test` command:
`php core/scripts/run-tests.sh --verbose --color --concurrency 4 --php `which php` --url http://msk.devl --directory ./modules/custom/msk_book`
