### ISSUE TITLE
Multiple @javascript tests break zombie.js

### ISSUE THREAD

**Issue by IslandUsurper** [phase2/grunt-drupal-tasks#125]
I've been writing tests in Behat for my Drupal site, and I've based my setup after the example/ folder here, so I'm running tests with Goutte and Zombie.js. However, as soon as I had a second Feature tagged `@javascript`, it throws this error:

```
      Server process has been terminated: (8) [
      events.js:72
              throw er; // Unhandled 'error' event
                    ^
      Error: listen EADDRINUSE
          at errnoException (net.js:904:11)
          at Server._listen2 (net.js:1042:14)
          at listen (net.js:1064:10)
          at net.js:1146:9
          at Object._onImmediate (node_modules/zombie/lib/zombie/dns_mask.js:69:16)
          at processImmediate [as _immediateCallback] (timers.js:345:15)
      ] (RuntimeException)
```

I assume this means that either zombie.js is trying to bind the same port for its browser, or to listen to my site twice and getting blocked. I haven't yet gotten into zombie's internals to figure it out, but I wanted to raise the issue about it. I'd really rather not have to give up grunt-parallel-behat, but since these tests are running on Jenkins, that's not (yet) a deal breaker.

**Comment by IslandUsurper** [comment]
Issue cross-posted at minkphp/MinkZombieDriver#126.

**Comment by IslandUsurper** [comment]
The Mink people said that specifying a different port for each process in grunt-parallel-behat ought to work, which I have requested at linusnorton/grunt-parallel-behat#12.

**Comment by grayside** [comment]
We are currently looking to switch to Phantom.js
