### ISSUE TITLE
The security-advisories package in example composer.json can break the build

### ISSUE THREAD

**Issue by jhedstrom** [phase2/grunt-drupal-tasks#130]
I recently had to remove the [security-advisories](https://github.com/phase2/grunt-drupal-tasks/blob/master/example/composer.json#L16) required packages from the example `composer.json` file in a project, because one of the security advisory projects had a broken `composer.json` file, which resulted in this error

```
Running "composer:install" (composer) task
Fatal error:
                                                                                                                                                                                                 
  [RuntimeException]                                                                                                                                                                             
  Could not load package socalnick/scn-social-auth in http://packagist.org: [UnexpectedValueException] Could not parse version constraint >=1.2.2 <2.0.0: Invalid version string "1.2.2 <2.0.0"  
                                                                                            
  [UnexpectedValueException]                                                                
  Could not parse version constraint >=1.2.2 <2.0.0: Invalid version string "1.2.2 <2.0.0"  
                                                                                               
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
```

Note, this package was not in use on the project in question. In fact, this error was triggered with the only required package being:

```
     "require": {
         "roave/security-advisories": "dev-master"
     }
```

**Comment by arithmetric** [comment]
This can be resolved by updating Composer by running: `composer self-update`

It is a rather nasty, known issue in the scn-social-auth package that they don't seem interested in fixing. See: https://github.com/SocalNick/ScnSocialAuth/commit/a12bbd6eb3e3ba949004e98d917690fa6a2e73ca#commitcomment-9355919

**Comment by jhedstrom** [comment]
Perfect. I think the version of composer on the Jenkins instance where this occurred was probably a bit old.
