### ISSUE TITLE
Suggestions on project workflow?

### ISSUE THREAD

**Issue by nvaken** [phase2/grunt-drupal-tasks#149]
I've been reviewing Grunt Drupal Tasks for some hours now and this seems to fit all my needs in Drupal development. Though I'm not entirely sure on how deployment would work with this setup. Say I have a project that I start with GDT, I suppose I create a new project repository and add the entire GDT setup to it (build folder and such are nicely ignored out of the box). When I'm done with development and need to deploy the project into production, how would one handle this particular flow? Would you need to pull in this entire GDT setup to a production server and rebuild there? Would you build it first into a separate environment and only migrate the build's data- and codebase? What kind of workflow would you suggest? 

I have some ideas how to get this to work, but I'd love some suggestions from people that are using this. Might this be worth adding to a seperate doc in the repo?

**Comment by grayside** [comment]
Hello nvaken,

The ideal of GDT is that you export the build/html directory with dereferenced symlinks and have a standalone piece of code you can push to your server any way you find useful. This allows you to avoid needing Ruby, Node, or any of the development dependencies on the production server. This can be repeated as needed for rolling updates from development to live.

If you like a good tarball, we already have the `grunt package` task that will prepare one for you from build/html.

We've been inching along a deployment support discussion in #24.

**Comment by nvaken** [comment]
Hi @grayside,

Thanks for the thorough answer, I managed to find the packaging functionality today and seems like a pretty straightforward solution. Thanks again for that! I think packaging is the way to go. 

I hope you don't mind me picking your brain a bit further here on this subject (this issue might actually prove worth to future visitors of this package). I was wondering how you would suggest managing user generated content within grunt-drupal-tasks? Untill now we simply synced the database from the leading install (mostly the production version) by using `drush` and it's alias system in combination of the sql functions. We also sync the complete user generated uploads folder (`sites/*/files`) from that same install. Are there any other better practices that you (or someone else) would recommend? If this is the way to go, does GDT support any easing of this process (managing aliases, syncing, etc..)?

Thanks again for your time! Much appreciated!

**Comment by grayside** [comment]
GDT does not currently have any "Drupal Management" functionality such as database management or really anything you might do with Drush beyond the make process. I've been talking to myself a bit in #98 about how to get some better support for these kinds of things built into GDT.

My current thinking is that those kinds of management scripts are far too subjective to bake into GDT, so I'm looking into creating a companion project that you can use to initialize projects with some starter scripts that will have GDT integration. This project informs how Drupal codebases are structured and facilitates quality and testing, but doesn't mandate how you manage Drupal as an application.

I have heard of specific project implementations extending the available grunt tasks in their own projects pretty easily--just define your own drush targets for whatever commands you need.

**Comment by nvaken** [comment]
Thanks again Grayside, for your feedback. Your above explanation makes sense. I'll be keeping an eye on your repositories to check on that future project. 

I might just pull this repo and customise some of the features in it to make it a bit more suitable for our needs. I can imagine adding some support for aliases on project basis. I'll be having to figure out how to do this in a structured way, but I think I'll manage!

**Comment by nvaken** [comment]
Hi @grayside, I still have a question (sorry). I'm thinking about how to implement grunt-drupal-tasks into our workflow. I hit some obvious walls here, like altering this project to implement our own make files. I'm not really sure how to extend this project without altering the repository. So I was already on my way of cloning this repository (and the `generator-gadget` repository) and altering it to fit our needs. Though, I'm really not comfortable by doing this. How would I extend this in a way that our colleagues still only need to fire `yo gadget` and get our own custom version of `grunt-drupal-tasks`? I was thinking about using git's submodule functionality somehow, but I don't see how that would actually be possible to implement our own make file, custom tasks and such? The EXTEND.md does not really enlighten me either.

**Comment by grayside** [comment]
Hi @nvaken

You should not need to edit any of the code to tailor these tools for your project.

`generator-gadget` is how you would start a new project. To retrofit an existing project to use GDT, you would want to adjust the organization of your project repository to better match the contents of the GDT examples/ directory. The goal of the generator is to do an initial setup that you would then edit and commit as you like.

You should not need to make any code changes to grunt-drupal-tasks to add custom functionality. Ultimately this project is itself a complex grunt plugin, and in your Gruntfile.js you can add more tasks or override what we've done. If you do want to use a fork, you can reference a git url in your package.json file.

Could you elaborate a bit on what you were thinking you needed to change?

**Comment by nvaken** [comment]
Again, thanks for the continuous help @grayside. Okay, so I'd best use generator-gadget to pull in the latest - unaltered - version of GDT? 

Do I understand it correctly that I do actually have to alter the generator to make it implement our custom tasks (eg. sequence of crush commands to pull in latest version of the project) and injecting a new project.make? Should I fork the generator and make sure my colleagues use that generator with "yo" to setup our standard Drupal install? Or could I do all that without forking the generator? 

Sorry if I'm a bit slow on this subject.

**Comment by grayside** [comment]
generator-gadget is intended to help jump-start initializing a repository. You don't need to use it at all. What's important is that your repository has the necessary files and configuration as demonstrated in the examples directory in this project.

On a per-project basis, if you want to add custom tasks it's easy to do so by creating code that's part of the project's own repository.

If you would like to use some combination of generator-gadget and grunt-drupal-tasks to provide a more specific starting place than what we have here, that's where things open up a bit. **You could fork generator-gadget, but it is also possible to chain yeoman generators.** I'm still learning about that myself so I have less specific guidance there.

We haven't established best practices on custom grunt tasks that should be reused across projects but aren't part of grunt-drupal-tasks itself, so while I'm interested in providing help this is an early case for us to learn from.

**Comment by nvaken** [comment]
Ah I see, it seems that I that I'd probably be better off forking both repositories. We're developing a lot of smaller websites, based on our own custom make files, a few custom private modules, etc... Also we've developed a few Drush commands which help us setup these smaller sites faster. Each project we develop is a new repository which is deployed on our development and production environment. Since we're seeking out some standardization concerning things like testing, compiling less files etc, we we're looking at Grunt Drupal Tasks, since this does almost everything we'd like to do. 

Using merely GDT out of the box would give us more work, making sure everything is in place manually (make files, tasks, etc..). So that's why I was searching for a way to still be able to get the main GDT repository and automatically merge that with our own custom code. 

Reading and interpreting your latest message it seems to be - for now - the best way will be to fork both repositories (`generator-gadget` and `grunt-drupal-tasks`) and customize those to our needs. Since chaining seems to be hard even for you, then I'd better just fork the whole lot. 

Thanks for all the help!
