### ISSUE TITLE
Add git hooks to enforce grunt validate on changed files

### ISSUE THREAD

**Issue by grayside** [phase2/grunt-drupal-tasks#151]
Allow for easy setup of git hooks on pre-commit to run grunt validate on files changed in the commit.

Maybe this is set up via a `grunt init` task.

I have looked into the [grunt-githooks](https://www.npmjs.com/package/grunt-githooks) plugin and I go back and forth whether it's worth the dependency. Anyone have opinions?

Possibly related to #143.

**Comment by markdboyd** [comment]
On a previous project, we implemented this ourselves using grunt-githooks. I found that it worked well, so I'd vote in favor of the dependency.

What other way would there by of generating the githooks files aside from grunt-githooks?

**Comment by grayside** [comment]
I've looked at the dependencies again and I think it's probably cleaner than rolling something custom as part of this project.

I've started considering this from the phpcs & incremental validation angle rather git hooks, which has led me to https://github.com/SaschaGalley/grunt-phpcs/issues/23.

**Comment by grayside** [comment]
I should add, I haven't assigned this to myself because I think setting up githooks can be done even if the commands triggered by pre-commit aren't efficient.

My latest thinking on that has been that we install the githooks if the main grunt build starts without a build/ directory already in place. We should make sure there is clear terminal output explaining that, as it's a side-effect that potentially conflicts with custom changes to the files.
