### ISSUE TITLE
Could not load package...

### ISSUE THREAD

**Issue by kalevitan** [phase2/grunt-drupal-tasks#162]
Hi, I was testing this out for the first time on my mac 10.9 and I got a package error for drush. 
```
Could not load package drush/drush in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^2.6.3: Invalid version string "^2.6.3"
```

I changed the version from "dev-master" to "master" and it seemed to work, but now there is another package issue. 
```
Could not load package bilge/doctrine-module in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^0.8: Invalid version string "^0.8"
```

What am I doing wrong or what is missing? I used the generator-gadget to build the source files.

Thanks

**Comment by arithmetric** [comment]
Hi @kalevitan,

This sounds like a known issue if you have an older version of Composer installed. Try resolving this by updating Composer by running: `composer self-update`

**Comment by kalevitan** [comment]
That solved it, @arithmetric. Thanks
