### ISSUE TITLE
Remove deprecated functionality for 1.0 release

### ISSUE THREAD

**Issue by grayside** [phase2/grunt-drupal-tasks#170]
There are a few things spread around the codebase in the name of backwards compatibility. Before releasing a 1.0 we should clear these out. For example, bundleInstall is still supported, though we have standardized on hyphenates over camelCase.

**Comment by arithmetric** [comment]
bundleInstall has been removed as part of #251.

Are there any other instances of deprecated functionality that still exist in the v1.0.0-pre branch?

**Comment by grayside** [comment]
A few instances appear in: https://github.com/phase2/grunt-drupal-tasks/search?utf8=%E2%9C%93&q=deprecated&type=Code

**Comment by arithmetric** [comment]
Nice use of the search feature!

#291 addresses these instances.
