### ISSUE TITLE
'grunt watch' does not leverage concurrent config

### ISSUE THREAD

**Issue by grayside** [phase2/grunt-drupal-tasks#172]
We have split watch functionality into frontend and backend commands using the concurrent plugin to keep the individual watch tasks fast. 

`grunt watch` to run all watch talks skips the parallelization.

To fix this, we might create a different task to watch all the things or rename the watch plugin with `grunt.renameTask ()` and claim "watch" as a roll up of all the watches.

**Comment by arithmetric** [comment]
While I'm not opposed to this being in the 1.0.0 release, I don't think it should be a release blocker. So I'm bumping its milestone.

**Comment by grayside** [comment]
Closing old issues that I do not expect to be tackled in the context of this project.
