### ISSUE TITLE
Replace Compass with node-sass

### ISSUE THREAD

**Issue by arithmetric** [phase2/grunt-drupal-tasks#184]
Replace Compass with node-sass in the default example to eliminate dependencies on Ruby and Bundler.

Support for Compass could be preserved in the Gadget generator as an option.

**Comment by grayside** [comment]
Unless #251, with it's implication that we cede frontend tasks to other tools via the theme dispatch system.

**Comment by arithmetric** [comment]
Closing since in #251 we've dropped built-in support for Compass.
