### ISSUE TITLE
grunt drush:liteinstall fails

### ISSUE THREAD

**Issue by smerth** [phase2/grunt-drupal-tasks#186]
```
grunt drush:liteinstall 
```
fails with message 
```
Cannot use GuzzleHttp\Ring\Client\Middleware as Middleware because the name is already in use in /Library/WebServer/Documents/drupal/grunt-test/d8-test/vendor/guzzlehttp/guzzle/src/Utils.php on line 7
```
anyone have any ideas about how to fix this? :palm_tree:

**Comment by jhedstrom** [comment]
Do you still get this if you run the latest (Beta15) Drupal 8 and Behat Drupal Extension (3.1.1)? Guzzle was updated which temporarily caused compatibility issues between Drupal 8 and the Behat Drupal Extension.

**Comment by jhedstrom** [comment]
I just saw this error, but it was on an older install. Once I added this line to composer.json:

```json
    "require-dev": {
        "guzzlehttp/guzzle" : "^6.0@dev"
```

and re-ran composer install, it went away (it was also still running beta14, which causes a different fatal error, so upgrading to beta 15 resolved that too).
