### ISSUE TITLE
Support for D8 composer install

### ISSUE THREAD

**Issue by grayside** [phase2/grunt-drupal-tasks#212]
Our current composer support focuses on development tools packaged at the repository root. Drupal 8 carries it's own composer file at it's project root. While D8 ships with the vendored libraries, it naturally does not ship with the dependencies of contrib modules.

We can initially defer on whether to support Composer Manager or develop D8 natively with composer, but we do need to support D8's composer mechanism more naturally.

**Comment by grayside** [comment]
Per @jhedstrom we should look into https://github.com/drupal-composer/drupal-project

**Comment by grayside** [comment]
After reading https://pantheon.io/blog/composer-vs-drush-make-which-should-you-use and considering the state of things, our immediate goal should be documentation or clear instructions on how composer manager can be woven into the build process. We can follow-up later with the more significant work of providing an option with GDT to use Composer without Drush Make.

**Comment by arithmetric** [comment]
This was addressed by #284.
