### ISSUE TITLE
Possible scope issue for this.name when running grunt install without --no-db-load

### ISSUE THREAD

**Issue by mirie** [phase2/grunt-drupal-tasks#225]
It appears that this.name is undefined. I think it's because the scope of this changes in this function here: https://github.com/phase2/grunt-drupal-tasks/blob/master/tasks/install.js#L60

**Comment by mirie** [comment]
PR = https://github.com/phase2/grunt-drupal-tasks/pull/226

**Comment by arithmetric** [comment]
Resolved with #226
