### ISSUE TITLE
Add drush site-audit to analyze task

### ISSUE THREAD

**Issue by grayside** [phase2/grunt-drupal-tasks#23]
Investigate addition of [Site Audit](https://www.drupal.org/project/site_audit) to the analyze task.

I expect we'll want plain text at minimum, html for generated report files, possibly leverage JSON output if we want fail conditions.

This may look like integration with a separated grunt-drupal-site-audit plugin.

**Comment by grayside** [comment]
Site Audit is somewhat redundant in purpose to GDT's own validate tasks, so it makes sense to look at what they do and replicate rather than attempting to integrate it.

**Comment by fluxsauce** [comment]
> so it makes sense to look at what they do and replicate rather than attempting to integrate it.
Well, that's unfortunate, I'm definitely willing to collaborate on building a better product.

**Comment by grayside** [comment]
Hi @fluxsauce!

We're excited you are following this issue queue so closely. I investigated Site Audit several months ago but forgot about this issue, so let me expand on the concerns and let's see if there is room for collaboration afterall.

### Pros

* We like the idea of reports being visible within Drupal, though our current reporting is mostly targeted at utility systems like Jenkins.
* We like the idea of a tool that can perform inspections specific to Drupal
* We could leverage the grunt drush integration to run the report mechanism.

### Cons

* All dependencies of GDT should be managed via bundler, npm, or composer. Drush commands need to be installed globally.
* We want to handle most tooling via node & grunt-based systems that we can run leanly and with specific controls, such as build-failing thresholds.

**Comment by fluxsauce** [comment]
> All dependencies of GDT should be managed via bundler, npm, or composer. Drush commands need to be installed globally.

Well, I had https://www.drupal.org/node/2425499 in my backlog, I'll work on that first.

Once that's sorted, I'll see what I can do about rolling a grunt task.

**Comment by fluxsauce** [comment]
> We like the idea of reports being visible within Drupal

To clarify, it's not actually visible within the Drupal installation; it's not actually a module, it's a Drush command that's intended to be used outside of Drupal to avoid the observer effect and to not require installation into the target site.

With that said, I've been asked a number of times about making it available within Drupal. Wasn't a super high priority when I first made it, but I can see the utility now in a few contexts. Just need to be careful about ensuring compatibility with platforms like Pantheon that have it installed globally.

**Comment by fluxsauce** [comment]
https://packagist.org/packages/drupal/site_audit

**Comment by grayside** [comment]
Not currently looking to expand the range of tools integrated into GDT.
