### ISSUE TITLE
`grunt package` is broken with g-d-t 0.11.x and grunt 1.x

### ISSUE THREAD

**Issue by smerrill** [phase2/grunt-drupal-tasks#274]
When a build is performed with them, sites/all/modules/custom and sites/all/themes/custom are empty.

**Comment by arithmetric** [comment]
Thanks for the report @smerrill. This seems to be related to changes in the glob dependency included with the Grunt 1.0.0 update. Prior to v4.0.0, node-glob followed symlinks.

**Comment by grayside** [comment]
The plan to switch to rsync will fix for non-Windows.

**Comment by arithmetric** [comment]
#275 is a solution that uses copy. I'll plan to release this as v0.11.1.
