### ISSUE TITLE
scaffolding fails when running grunt. 

### ISSUE THREAD

**Issue by javasavvy** [phase2/grunt-drupal-tasks#287]
I have followed the directions in the generator-gadget project was able to get the Yeoman generator to generate the project.  Next I try running grunt, but I get an error Running "scaffold" task "Fatal error: Cannot apply scaffolding until after Drupal has been built.

I also get a warning that drush:make failed so I guess this this could be the root problem?

I am running this from a windows 10 machine, but can not figure out what is going wrong.  I'm new to drupal and grunt and could use some help.

Thanks!

**Comment by jhedstrom** [comment]
This should be fixed in alpha 2.
