### ISSUE TITLE
Allow changing vendor path for package output

### ISSUE THREAD

**Issue by arithmetric** [phase2/grunt-drupal-tasks#288]
When a Composer based build is packaged, the paths in the autoloader files generated by Composer should be updated to match the structure of the package output.

The goals are:

- It should be possible to created package output that can live in the docroot without references outside the docroot.

- It should also be possible to configure the vendor directory to live at the same level as the docroot.

Follow up from #284.

**Comment by arithmetric** [comment]
I created this branch with comments on a possible approach to this issue:
https://github.com/phase2/grunt-drupal-tasks/compare/feature/package_rewrite_composer

I'd welcome feedback on the best approach for this. @jhedstrom @grayside @mike-potter

**Comment by grayside** [comment]
I missed the last update here, will check it out soon.

In the meantime, Pantheon may have simplified the problem just recently: https://pantheon.io/docs/nested-docroot/

**Comment by grayside** [comment]
In review of the proposed approach I think it's on the right track. If the GDT buildpath does not match the configured package docroot it is set up to rewrite the composer.json before re-running the `composer install` we put in place to remove dev dependencies.

I have potentially breaking changes in mind with #255 and #24 but nothing I see here is out of the way for those changes to similarly support.

**Comment by mike-potter** [comment]
Created a PR for this here: https://github.com/phase2/grunt-drupal-tasks/pull/297

Closing this issue since we can discuss it now in the PR.
