### ISSUE TITLE
Remove Composer dev dependencies from package output

### ISSUE THREAD

**Issue by arithmetric** [phase2/grunt-drupal-tasks#289]
When a Composer based build is packaged, development dependencies in `composer.json` should be excluded from the vendor resources included in the package output.

Follow up from #284.

**Comment by jhedstrom** [comment]
We should also regenerate the autoload files so they don't include the dev dependencies. This may be automatically done depending on how we remove them (otherwise `composer dump-autoload --no-dev` would do it).

**Comment by grayside** [comment]
If we end up running dump-autoload for a package, should we also run with `--optimize`?

This still leads to pushing the dev dependencies, I found `composer remove --update-no-dev` as a possibility, though I haven't tested to see if that's frustratingly slow.

**Comment by jhedstrom** [comment]
In manual testing, running `composer install --no-dev` works, and is super fast. We could run this *after* packaging so as not to change the local install.

**Comment by jhedstrom** [comment]
This is merged now.
