### ISSUE TITLE
Composer Scaffolding fails when a composer.lock file exists

### ISSUE THREAD

**Issue by ndrake86** [phase2/grunt-drupal-tasks#292]
In GDT 1.0-alpha if a composer.lock file exists the grunt task will execute composer:install and attempt to run the composer:drupal-scaffold task. When that process runs the following error is thrown. 

```
Running "composer:drupal-scaffold" (composer) task
> DrupalComposer\DrupalScaffold\Plugin::scaffold
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Composer\Installer\InstallationManager::getInstallPath() must implement interface Composer\Package\PackageInterface, null given, called in /var/www/vendor/drupal-composer/drupal-scaffold/src/Handler.php on line 205 and defined in phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:227
Stack trace:
#0 /var/www/vendor/drupal-composer/drupal-scaffold/src/Handler.php(205): Composer\Installer\InstallationManager->getInstallPath(NULL)
#1 /var/www/vendor/drupal-composer/drupal-scaffold/src/Handler.php(102): DrupalComposer\DrupalScaffold\Handler->getWebRoot()
#2 /var/www/vendor/drupal-composer/drupal-scaffold/src/Plugin.php(77): DrupalComposer\DrupalScaffold\Handler->downloadScaffold()
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(255): DrupalComposer\DrupalScaffold\Plugin::scaffold(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(209): Composer\Event in phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php on line 227
```

Removing the lock file so that the process runs the composer:update task does not cause the scaffold task to fail.

**Comment by jhedstrom** [comment]
hmm, we need the scaffold task to run after install, because otherwise none of those files in the docroot would be downloaded for devs that are running once there is a `composer.lock` file. We also don't want to run `composer update` automatically except for the first install. Running that to update the lock file should always be intentional. I'll see if I can figure out what's going on with that error.

**Comment by ndrake86** [comment]
Yes this can be closed.

**Comment by ndrake86** [comment]
This was a bad configuration on my part @jhedstrom thanks for the help closing out.
