### ISSUE TITLE
Issue in eslint.js task in GDT alpha2

### ISSUE THREAD

**Issue by ndrake86** [phase2/grunt-drupal-tasks#295]
With a clean install of `GDT alpha2` there is currently and issue with the `eslint.js` task which breaks the grunt validate task. I believe the issue is that the `grunt-eslint` task no longer has `eslint` available to the task as eslint is no available to in the node_modules directory within `grunt-eslint`. When running the validate task here is the output: 

```
grunt validate
Loading "eslint.js" tasks...ERROR
>> Error: Cannot find module 'eslint'

Running "notify_hooks" task

Running "validate" task
Warning: Task "eslint:validate" not found. Use --force to continue.

Aborted due to warnings.
```
This is of course on a clean install of GDT alpha2. Updating from alpha1 to alpha2 this does not seem to be an issue.

**Comment by ndrake86** [comment]
The issue looks to be with the eslint package version 3.1.1. 
```
npm ERR! Linux 2.6.32-642.1.1.el6.x86_64
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.4.7/bin/node" "/home/vagrant/.nvm/versions/node/v4.4.7/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path /var/www/node_modules/grunt-drupal-tasks/node_modules/eslint/node_modules/levn/package.json.3357009142
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/var/www/node_modules/grunt-drupal-tasks/node_modules/eslint/node_modules/levn/package.json.3357009142' -> '/var/www/node_modules/grunt-drupal-tasks/node_modules/eslint/node_modules/levn/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/node_modules/grunt-drupal-tasks/npm-debug.log
```

**Comment by ndrake86** [comment]
Down-leveling the version of `eslint` in the `package.json` file seems to fix this issue
`eslint@3.1.0 node_modules/eslint`

**Comment by jhedstrom** [comment]
Apparently the `eslint` package just isn't installed correctly by `npm install`. After manually installing (`npm install eslint`) the errors go away.

**Comment by jhedstrom** [comment]
I got this working by switching from node v4.4.7 to v6.2.1. No idea really why, but @grayside mentioned that we might have uncovered an edge case in how nvm v2 handles dependencies and dev dependency conflicts.

Not sure if there's much we can do other than recommend higher node versions?

**Comment by arithmetric** [comment]
I ran into this issue today and tracked it down to an issue with how npm v2 creates shrinkwrap files. See: https://github.com/npm/npm/issues/4161

This led to the shrinkwrap file not including eslint, which is a required dependency of grunt-eslint, because it is a dev dependency of grunt-drupal-tasks.

I've committed a regenerated shrinkwrap to master that uses a process to workaround this issue.

**Comment by arithmetric** [comment]
Please re-open if you find this happening with the latest master version.
