### ISSUE TITLE
Drupal 8.2 requires a /profiles directory

### ISSUE THREAD

**Issue by mike-potter** [phase2/grunt-drupal-tasks#304]
When there isn't any src/profiles then the Drupal /profiles directory does not get created:

Running "symlink:profiles" (symlink) task
>> Created 0 symbolic links.

In Drupal 8.2, this causes an error:

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/home/travis/build/phase2/grunt-drupal-tasks/test/working_copy/build/html/profiles): failed to open dir: No such file or directory' in /home/travis/build/phase2/grunt-drupal-tasks/test/working_copy/build/html/core/tests/bootstrap.php:23

Currently causing our travis tests to fail.

**Comment by mike-potter** [comment]
Addressing this issue in https://github.com/phase2/grunt-drupal-tasks/pull/305.

**Comment by grayside** [comment]
To be clear, in Drupal 8 the top-level profiles directory doesn't exist by default? There's nothing in GDT that is responsible for creating or removing that directory to my knowledge.

**Comment by mike-potter** [comment]
Correct.  In Drupal 8.1, not having a /profiles directory did not cause a problem.  I submitted https://www.drupal.org/node/2812607#comment-11698201 as a core issue for this regression in 8.2.  But no reason not to ensure the directories get created.  Nothing in drupal core is responsible for creating /profiles.  It just comes are part of the tar.gz, but not when you reference core in composer.json and not done by drupal-scaffold.  If there isn't any custom profile in /src/profiles, the /profiles dir was not created by gdt.

**Comment by arithmetric** [comment]
Fixed by #305.
