### ISSUE TITLE
Releasing 1.0.0 stable

### ISSUE THREAD

**Issue by mike-potter** [phase2/grunt-drupal-tasks#307]
Please list any release blockers for the 1.0 stable.  Milestone looks complete.  Docs have been updated here: https://phase2.github.io/grunt-drupal-tasks/

Are we waiting for anything else?

**Comment by grayside** [comment]
Indeed, looking good.

I think we can cut a release soon. I'll see if I have time to take it for a spin on my D8/non-composer project today to confirm things are good in reality, but that can just as well be used to scout for 1.0.1 fixes :)

**Comment by arithmetric** [comment]
I'm ready for the 1.0.0 release. I can push it out at 12pm EST tomorrow unless something critical comes up.

**Comment by jhedstrom** [comment]
👍

**Comment by arithmetric** [comment]
1.0.0 is released!

**Comment by mike-potter** [comment]
Woot!
