### ISSUE TITLE
Create Yeoman generator for project set up

### ISSUE THREAD

**Issue by arithmetric** [phase2/grunt-drupal-tasks#35]
Let's explore options to spin off the current example template into a more flexible and interactive starting point using [grunt-init](http://gruntjs.com/project-scaffolding) or [Yeoman](http://yeoman.io/).

**Comment by grayside** [comment]
I wonder if we can borrow from or collaborate with Hedley

* http://www.gizra.com/content/yo-hedley/
* http://www.gizra.com/content/phantomcss-ui-regression/
* https://github.com/Gizra/generator-hedley

**Comment by arithmetric** [comment]
This has been started: https://github.com/phase2/generator-gadget

Let's close this once we have documentation in this project about it.

**Comment by arithmetric** [comment]
Documentation has been added: https://github.com/phase2/grunt-drupal-tasks/blob/master/CONFIG.md#start-using-gadget
