### ISSUE TITLE
Use Flow for JS Type Checking

### ISSUE THREAD

**Issue by febbraro** [phase2/grunt-drupal-tasks#62]
Flow http://flowtype.org/ is an intersting tool that does Javascript type checking. This can help find a lot of errors that are hard to spot initially. It does not require you to do anything different to your code than add a comment at the top.  Eventually it can support transitioning to a more explicit typing.

**Comment by grayside** [comment]
This looks really cool, but I don't think we want an active dependency on another programming language, or handle the grunt integration for a complex tool in this project.

**Comment by grayside** [comment]
Closing old issues that I do not expect to be tackled in the context of this project.
