### ISSUE TITLE
Add test for compass functionality

### ISSUE THREAD

**Issue by grayside** [phase2/grunt-drupal-tasks#69]
Let's add some test coverage that compass is working, which incidentally should cover bundleInstall.

Doing so will require:

* A Gemfile to pull in compass dependencies.
* A Drupal theme-like structure that will allow testing config.rb & sass compilation, but does not otherwise need to be functional.
* Code to set up the above two things as part of the working copy for testing.
* A mocha to look for a generated CSS file.

We do not want these changes built directly into the examples folder, as examples should remain available as a stripped down template for starting projects, and SASS functionality should not be part of that.

**Comment by arithmetric** [comment]
Please review #108 as a fix for this issue.
